### ISSUE TITLE
Implement component for single entities

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-vue-components#13]
We have components such as SupportedFileFormats, SupportedServiceTypes, which all list parts of the data.

Implement full support and show (optionally) all information. Allow a component to only show information for a single entity, e.g. information for a single FileFormat.

Also, rename SupportedFileFormats and SupportedServiceTypes (remove "Supported").

**Comment by christophfriedrich** [comment]
For the list components, please continue to provide an option that displays everything like it is right now, i.e. that just lists the simple names -- because I don't think that the Hub needs the possibility to show *all* the detailed information.

This could be done via a prop named `simple` or `details` that accepts a Boolean value.

**Comment by m-mohr** [comment]
see #29
